DoAn_LTWeb/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoAn_LTWeb.Models;
using System.IO;
using System.Data.Entity;
using System.Net;
using DoAn_LTWeb.ViewModels;
using System.Data.SqlClient;
namespace DoAn_LTWeb.Controllers
{
    public class AdminController : Controller
    {
        INSTRUMENT db = new INSTRUMENT();
        public ActionResult Index()
        {
            ViewBag.Title = "Tổng quan";

            ViewBag.ProductCount = db.SANPHAMs.Count();

            ViewBag.CategoryCount = db.LOAISANPHAMs.Count();

            ViewBag.OrderCount = db.DONDATHANGs.Count();

            ViewBag.CustomerCount = db.KHACHHANGs.Count(k => k.MAVAITRO == 2);

            ViewBag.AccountCount = db.KHACHHANGs.Count(k => k.MAVAITRO == 1);

            ViewBag.NewReportCount = db.DONDATHANGs.Count(d => d.TRANGTHAIDON == "Chờ xử lý");

            return View();
        }
        public ActionResult Products(string searchQuery, int? categoryId, int? brandId)
        {
            var sANPHAMs = db.SANPHAMs.Include(s => s.LOAISANPHAM).Include(s => s.THUONGHIEU).AsQueryable();

            if (!String.IsNullOrEmpty(searchQuery))
            {
                string lowerSearch = searchQuery.ToLower();
                sANPHAMs = sANPHAMs.Where(s => s.TENSP.ToLower().Contains(lowerSearch));
            }
            if (categoryId.HasValue)
            {
                var childrenIds = db.LOAISANPHAMs
                                    .Where(c => c.MALOAICHA == categoryId.Value)
                                    .Select(c => c.MALOAI)
                                    .ToList();
                childrenIds.Add(categoryId.Value);
                sANPHAMs = sANPHAMs.Where(s => s.MALOAI.HasValue && childrenIds.Contains(s.MALOAI.Value));
            }
            if (brandId.HasValue)
            {
                sANPHAMs = sANPHAMs.Where(s => s.MATHUONGHIEU == brandId);
            }

            ViewBag.MALOAI = new SelectList(db.LOAISANPHAMs.Where(l => l.MALOAICHA == null), "MALOAI", "TENLOAI", categoryId);
            ViewBag.MATHUONGHIEU = new SelectList(db.THUONGHIEUs, "MATHUONGHIEU", "TENTHUONGHIEU", brandId);
            ViewBag.CurrentSearch = searchQuery;



            return View(sANPHAMs.ToList());
        }

        public ActionResult CreateProduct()
        {
            ViewBag.Title = "Thêm sản phẩm mới";
            ViewBag.MALOAI = new SelectList(db.LOAISANPHAMs.Where(l => l.MALOAICHA != null), "MALOAI", "TENLOAI");
            ViewBag.MATHUONGHIEU = new SelectList(db.THUONGHIEUs, "MATHUONGHIEU", "TENTHUONGHIEU");

            var viewModel = new ProductCreateViewModel
            {
                SanPham = new SANPHAM(),
                BienThe = new SANPHAM_BIENTHE() 
            };

            return View(viewModel);
        }


          [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateProduct(ProductCreateViewModel viewModel) 
        {
            ViewBag.Title = "Thêm sản phẩm mới";
            ViewBag.MALOAI = new SelectList(db.LOAISANPHAMs.Where(l => l.MALOAICHA != null), "MALOAI", "TENLOAI", viewModel.SanPham.MALOAI);
            ViewBag.MATHUONGHIEU = new SelectList(db.THUONGHIEUs, "MATHUONGHIEU", "TENTHUONGHIEU", viewModel.SanPham.MATHUONGHIEU);

            try
            {
                string tenFileAnh = null; 
                if (viewModel.AnhBiaFile != null && viewModel.AnhBiaFile.ContentLength > 0)
                {
                    tenFileAnh = Path.GetFileName(viewModel.AnhBiaFile.FileName);
                    tenFileAnh = Guid.NewGuid().ToString().Substring(0, 8) + "_" + tenFileAnh;

                    string pathLuuFile = Path.Combine(Server.MapPath("~/Content/Assets/Product_Images"), tenFileAnh);
                    viewModel.AnhBiaFile.SaveAs(pathLuuFile);
                }
                //GỌI PROCEDURE THÊM SẢN PHẨM
                        db.Database.ExecuteSqlCommand(
                    "EXEC sp_THEMSANPHAM @MASP, @TENSP, @MALOAI, @MATHUONGHIEU, @MOTA, @ANHBIA, @TENBIENTHE, @GIAGOC, @GIABAN, @SOLUONGTON",
                    new SqlParameter("@MASP", viewModel.SanPham.MASP),
                    new SqlParameter("@TENSP", viewModel.SanPham.TENSP),
                    new SqlParameter("@MALOAI", (object)viewModel.SanPham.MALOAI ?? DBNull.Value),
                    new SqlParameter("@MATHUONGHIEU", (object)viewModel.SanPham.MATHUONGHIEU ?? DBNull.Value),
                    new SqlParameter("@MOTA", (object)viewModel.SanPham.MOTA ?? DBNull.Value),
                    new SqlParameter("@ANHBIA", (object)tenFileAnh ?? DBNull.Value),
                    new SqlParameter("@TENBIENTHE", viewModel.BienThe.TENBIENTHE),
                    new SqlParameter("@GIAGOC", viewModel.BienThe.GIAGOC),
                    new SqlParameter("@GIABAN", viewModel.BienThe.GIABAN),
                    new SqlParameter("@SOLUONGTON", viewModel.BienThe.SOLUONGTON)
                );


                //GỌI PROCEDURE CHO LIST_ANHSP
                if (viewModel.GalleryFiles != null && viewModel.GalleryFiles.Any())
                {
                    foreach (var file in viewModel.GalleryFiles)
                    {
                        if (file != null && file.ContentLength > 0)
                        {
                            // a. Lưu file ảnh gallery
                            string tenFileGallery = Path.GetFileName(file.FileName);
                            tenFileGallery = Guid.NewGuid().ToString().Substring(0, 8) + "_" + tenFileGallery;
                            string pathLuuFileGallery = Path.Combine(Server.MapPath("~/Content/Assets/Product_Images"), tenFileGallery);
                            file.SaveAs(pathLuuFileGallery);

                            // b. GỌI SP_THEM_ANHSP cho từng ảnh
                            db.Database.ExecuteSqlCommand(
                                "EXEC SP_THEM_ANHSP @MASP, @URL_ANH",
                                new SqlParameter("@MASP", viewModel.SanPham.MASP), 
                                new SqlParameter("@URL_ANH", tenFileGallery)
                            );
                        }
                    }
                }
                return RedirectToAction("Products");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Đã xảy ra lỗi: " + ex.Message);
            }
            return View(viewModel);
        }


        public ActionResult EditProduct(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SANPHAM product = db.SANPHAMs.Find(id);

            if (product == null)
            {   
                return HttpNotFound();
            }

            SANPHAM_BIENTHE variant = db.SANPHAM_BIENTHE.FirstOrDefault(v => v.MASP == id);
            if (variant == null)
            {
                // (Xử lý nếu Vỏ có mà Ruột không có -> nên tạo 1 Ruột rỗng)
                variant = new SANPHAM_BIENTHE { MASP = id };
            }

            var viewModel = new ProductCreateViewModel
            {
                SanPham = product,
                BienThe = variant
            };


            ViewBag.MALOAI = new SelectList(db.LOAISANPHAMs.Where(l => l.MALOAICHA != null), "MALOAI", "TENLOAI", product.MALOAI);
            ViewBag.MATHUONGHIEU = new SelectList(db.THUONGHIEUs, "MATHUONGHIEU", "TENTHUONGHIEU", product.MATHUONGHIEU);

            ViewBag.Title = "Chỉnh sửa sản phẩm";
            return View(viewModel);
        }





        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditProduct(ProductCreateViewModel viewModel)
        {
            ViewBag.MALOAI = new SelectList(db.LOAISANPHAMs.Where(l => l.MALOAICHA != null), "MALOAI", "TENLOAI", viewModel.SanPham.MALOAI);
            ViewBag.MATHUONGHIEU = new SelectList(db.THUONGHIEUs, "MATHUONGHIEU", "TENTHUONGHIEU", viewModel.SanPham.MATHUONGHIEU);


            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            string tenFileAnh = viewModel.SanPham.ANHBIA;
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(viewModel);
                }

                db.Database.ExecuteSqlCommand(
                    "EXEC SP_SUASANPHAM @MASP, @MABIENTHE, @TENSP, @MALOAI, @MATHUONGHIEU, @MOTA, @ANHBIA, @TENBIENTHE, @GIAGOC, @GIABAN, @SOLUONGTON",
                    new SqlParameter("@MASP", viewModel.SanPham.MASP), // Key Vỏ
                    new SqlParameter("@MABIENTHE", viewModel.BienThe.MABIENTHE), // Key Ruột

                    new SqlParameter("@TENSP", viewModel.SanPham.TENSP),
                    new SqlParameter("@MALOAI", (object)viewModel.SanPham.MALOAI ?? DBNull.Value),
                    new SqlParameter("@MATHUONGHIEU", (object)viewModel.SanPham.MATHUONGHIEU ?? DBNull.Value),
                    new SqlParameter("@MOTA", (object)viewModel.SanPham.MOTA ?? DBNull.Value),
                    new SqlParameter("@ANHBIA", (object)tenFileAnh ?? DBNull.Value),

                    new SqlParameter("@TENBIENTHE", viewModel.BienThe.TENBIENTHE),
                    new SqlParameter("@GIAGOC", viewModel.BienThe.GIAGOC),
                    new SqlParameter("@GIABAN", viewModel.BienThe.GIABAN),
                    new SqlParameter("@SOLUONGTON", viewModel.BienThe.SOLUONGTON)
                         );

                if (viewModel.GalleryFiles != null && viewModel.GalleryFiles.Any())
                {
                    foreach (var file in viewModel.GalleryFiles)
                    {
                        if (file != null && file.ContentLength > 0)
                        {
                            // a. Lưu file ảnh gallery
                            string tenFileGallery = Path.GetFileName(file.FileName);

DoAn_LTWeb/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DoAn_LTWeb.ViewModels;
using DoAn_LTWeb.Models;

namespace DoAn_LTWeb.Controllers
{
    public class CartController : Controller
    {

        INSTRUMENT data = new INSTRUMENT();

       private List<CartItemViewModel> GetCart()
        {
            var cart = Session["GioHang"] as List<CartItemViewModel>;
            if (cart == null)
            {
                cart = new List<CartItemViewModel>();
                Session["GioHang"] = cart;
            }
            return cart;
        }


        //giỏ hàng
        public ActionResult Index()
        {
            var cart = GetCart();
            ViewBag.TongTien = cart.Sum(item => item.ThanhTien);
            return View(cart);
        }


        //thêm vào giỏ hàng
        [HttpPost]
        public ActionResult AddToCart(int variantID, int quantity, string type)
        {

            //lấy thông tin biến thể sản phẩm 
            var variant = data.SANPHAM_BIENTHE.Find(variantID);
            if (variant == null)
            {
                return HttpNotFound();
            }
            //Lấy thông tin sản phẩm cha
            var product = data.SANPHAMs.Find(variant.MASP);
            string images = !string.IsNullOrEmpty(variant.ANH_BIENTHE)
                                                    ? variant.ANH_BIENTHE
                                                    :product.ANHBIA;
            var cart = GetCart();
            var item = cart.FirstOrDefault(i => i.MaBienThe == variantID);
            if (item !=null)
            {
                //nếu có rồi thì tăng số lượng
                item.SoLuong += quantity;
            }
            else
            {
                cart.Add(new CartItemViewModel
                {
                    MaBienThe = variant.MABIENTHE,
                    TenSanPham = product.TENSP,
                    TenBienThe = variant.TENBIENTHE,
                    HinhAnh = images,
                    DonGia = variant.GIABAN ?? 0,
                    SoLuong = quantity
                });

            }


            Session["GioHang"] = cart;
            if (type == "buynow")
            {
                return RedirectToAction("Checkout"); //đến trang thanh toán
            }
            else
            {
                TempData["SuccessMessage"] = "Đã thêm vào giỏ hàng thành công!";
                if (Request.UrlReferrer != null)
                {
                    return Redirect(Request.UrlReferrer.ToString());
                }
                return RedirectToAction("Details", "Store", new { id = product.MASP });
            }
        }


        //THÔNG BÁO thành công khi đặt hàng 
        public ActionResult OrderSuccess()
        {
            // Trả về View OrderSuccess.cshtml
            return View();
        }




        //cập nhật số lượng
        [HttpPost]
        public ActionResult UpdateQuantity(int id, int quantity)
        {
            var cart = GetCart();
            var item = cart.FirstOrDefault(x => x.MaBienThe == id);
            if (item != null)
            {
                item.SoLuong = quantity;
            }
            return RedirectToAction("Index");
        }







        //xóa sản phẩm
        public ActionResult Remove(int id)
        {
            var cart = GetCart();
            var item = cart.FirstOrDefault(x => x.MaBienThe == id);
            if (item != null)
            {
                cart.Remove(item);
            }
            return RedirectToAction("Index");
        }
        //thanh toán
        public ActionResult Checkout()
        {
            var cart = GetCart();
            if (cart.Count == 0) return RedirectToAction("Index", "Home");

            ViewBag.TongTien = cart.Sum(x => x.ThanhTien);
            return View(cart); // Trả về View để điền thông tin
        }




    }
}

DoAn_LTWeb/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Trang Quản Trị</title>
    <script src="https://cdn.tailwindcss.com"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">


    <style>
        body {
            font-family: 'Inter', sans-serif;
        }
    </style>

</head>
<body class="bg-gray-100">

    <div class="flex h-screen">
        <!-- ===== Thanh bên (Sidebar) ===== -->
        <aside id="sidebar" class="fixed inset-y-0 left-0 z-30 w-64 bg-gray-900 text-white flex-col
                                     transform -translate-x-full md:translate-x-0
                                     transition-transform duration-300 ease-in-out shadow-lg">

            <!-- Logo/Header của Sidebar -->
            <div class="flex items-center justify-center p-5 h-20 border-b border-gray-700">
                <i class="fas fa-guitar fa-2x text-blue-400"></i>
                <span class="text-2xl font-bold ml-3">Admin Instrument</span>
            </div>

            <!-- Menu điều hướng -->
            <nav class="flex-1 overflow-y-auto pt-4">
                <ul class="space-y-2 px-4">
                    <!-- Mục: Trang chủ -->
                    <li>
                        <a href="@Url.Action("Index", "Admin")" class="flex items-center p-3 text-base rounded-lg text-gray-300 hover:bg-gray-700 hover:text-white transition-colors group">
                            <i class="fas fa-home w-6 h-6 text-gray-400 group-hover:text-white"></i>
                            <span class="ml-3">Trang chủ</span>
                        </a>
                    </li>

                    <!-- Tiêu đề nhóm -->
                    <li class="px-3 pt-4 pb-2 text-xs font-semibold text-gray-400 uppercase tracking-wider">
                        Quản lý Kho Hàng
                    </li>
                    <!-- Mục 2.2: Quản lý Sản phẩm -->
                    <li>
                        <a href="@Url.Action("Products", "Admin")" class="flex items-center p-3 text-base rounded-lg text-gray-300 hover:bg-gray-700 hover:text-white transition-colors group">
                            <i class="fas fa-box-open w-6 h-6 text-gray-400 group-hover:text-white"></i>
                            <span class="ml-3">Quản lý Sản phẩm</span>
                        </a>
                    </li>
                    <!-- Mục 2.2: Quản lý Loại sản phẩm -->
                    <li>
                        <a href="@Url.Action("Categories", "Admin")" class="flex items-center p-3 text-base rounded-lg text-gray-300 hover:bg-gray-700 hover:text-white transition-colors group">
                            <i class="fas fa-sitemap w-6 h-6 text-gray-400 group-hover:text-white"></i>
                            <span class="ml-3">Quản lý Loại sản phẩm</span>
                        </a>
                    </li>

                    <!-- Tiêu đề nhóm -->
                    <li class="px-3 pt-4 pb-2 text-xs font-semibold text-gray-400 uppercase tracking-wider">
                        Quản lý Bán Hàng
                    </li>
                    <!-- Mục 2.3: Quản lý Đơn hàng -->
                    <li>
                        <a href="@Url.Action("Orders", "Admin")" class="flex items-center p-3 text-base rounded-lg text-gray-300 hover:bg-gray-700 hover:text-white transition-colors group">
                            <i class="fas fa-shopping-cart w-6 h-6 text-gray-400 group-hover:text-white"></i>
                            <span class="ml-3">Quản lý Đơn hàng</span>
                        </a>
                    </li>
                    <!-- Mục 2.4: Quản lý Khách hàng -->
                    <li>
                        <a href="@Url.Action("Customers", "Admin")" class="flex items-center p-3 text-base rounded-lg text-gray-300 hover:bg-gray-700 hover:text-white transition-colors group">
                            <i class="fas fa-users w-6 h-6 text-gray-400 group-hover:text-white"></i>
                            <span class="ml-3">Quản lý Khách hàng</span>
                        </a>
                    </li>

                    <!-- Tiêu đề -->
                    <li class="px-3 pt-4 pb-2 text-xs font-semibold text-gray-400 uppercase tracking-wider">
                        Hệ Thống
                    </li>

                    <!-- Mục 2.5: Thống kê và Báo cáo  -->
                    <li>
                        <a href="@Url.Action("Statistics", "Admin")" class="flex items-center p-3 text-base rounded-lg text-gray-300 hover:bg-gray-700 hover:text-white transition-colors group">
                            <i class="fas fa-chart-line w-6 h-6 text-gray-400 group-hover:text-white"></i>
                            <span class="ml-3">Thống kê & Báo cáo</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </aside>
        <div class="flex-1 flex flex-col md:ml-64 transition-all duration-300 ease-in-out">
            @RenderBody()
            <main class="flex-1 overflow-y-auto p-6">
            </main>
        </div>
    </div>

    <!-- Lớp phủ mờ khi mở menu di động -->
    <div id="sidebar-overlay" class="fixed inset-0 bg-black bg-opacity-50 z-20 md:hidden hidden"></div>

    <script>
        const menuToggle = document.getElementById('menu-toggle');
        const sidebar = document.getElementById('sidebar');
        const sidebarOverlay = document.getElementById('sidebar-overlay');

        function toggleSidebar() {
            sidebar.classList.toggle('-translate-x-full');
            sidebarOverlay.classList.toggle('hidden');
        }

        menuToggle.addEventListener('click', toggleSidebar);
        sidebarOverlay.addEventListener('click', toggleSidebar);
    </script>

    @RenderSection("scripts", required: false)
</body>
</html>

DoAn_LTWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MusicShop</title>
    <link href="~Content/Site.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>

    <header>
        <div class="bg-black border-bottom py-2 d-none d-lg-block">
            <div class="container d-flex justify-content-end">
                <span class="text-light small me-3">
                    <i class="fas fa-phone me-1"></i> Hotline: 1800 1234
                </span>
                <span class="text-light small">
                    <i class="fas fa-envelope me-1"></i> Email: info@musicshop.com
                </span>
            </div>
        </div>

        <nav class="navbar navbar-expand-lg navbar-light bg-warning shadow-sm sticky-top">
            <div class="container">

                <a class="navbar-brand fw-bold text-danger" href="@Url.Action("Index", "Home")">
                    MusicShop
                </a>
                <div class="collapse navbar-collapse" id="mainNavbarCollapse">

                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        @Html.Action("_HeaderMenu", "Home")
  
                    </ul>

                    <form class="d-flex mx-lg-auto" style="width: 300px;">
                        <input class="form-control me-2" type="search" placeholder="Bạn tìm gì...">
                        <button class="btn btn-outline-danger" type="submit"><i class="fas fa-search"></i></button>
                    </form>

                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            @Html.ActionLink("Giỏ hàng (0)", "Index", "Cart", null, new { @class = "nav-link" })
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="pb-3">
        @RenderBody()
    </main>

    <footer class="bg-dark text-white pt-5 pb-3">
        <div class="container">
            <div class="row">

                <div class="col-lg-3 col-md-6 mb-4">
                    <h4 class="text-uppercase mb-3">Về MusicShop</h4>
                    <p class="text-white-50">Cửa hàng nhạc cụ chính hãng. Sứ mệnh của chúng tôi là mang âm nhạc đến mọi nhà.</p>
                </div>

                <div class="col-lg-3 col-md-6 mb-4">
                    <h4 class="text-uppercase mb-3">Hỗ trợ khách hàng</h4>
                    <ul class="list-unstyled">
                        <li><a href="#" class="text-white-50 text-decoration-none">Hướng dẫn mua hàng</a></li>
                        <li><a href="#" class="text-white-50 text-decoration-none">Chính sách bảo hành</a></li>
                        <li><a href="#" class="text-white-50 text-decoration-none">Tra cứu đơn hàng</a></li>
                    </ul>
                </div>

                <div class="col-lg-3 col-md-6 mb-4">
                    <h4 class="text-uppercase mb-3">Liên hệ</h4>
                    <p class="text-white-50"><i class="fas fa-map-marker-alt me-2"></i> 123 Đường ABC, Q.1, TPHCM</p>
                    <p class="text-white-50"><i class="fas fa-phone me-2"></i> 1800 1234</p>
                    <p class="text-white-50"><i class="fas fa-envelope me-2"></i> info@musicshop.com</p>
                </div>

                <div class="col-lg-3 col-md-6 mb-4">
                    <h4 class="text-uppercase mb-3">Theo dõi chúng tôi</h4>
                    <a href="#" class="text-white fs-4 me-2"><i class="fab fa-facebook-f"></i></a>
                    <a href="#" class="text-white fs-4 me-2"><i class="fab fa-youtube"></i></a>
                    <a href="#" class="text-white fs-4 me-2"><i class="fab fa-instagram"></i></a>
                </div>
            </div>

            <div class="row">
                <div class="col-12 text-center border-top border-secondary pt-3 mt-3">
                    <p class="text-white-50">&copy; @DateTime.Now.Year MusicShop. Đồ án môn Lập trình Web.</p>
                </div>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>